POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Manish kr sinha",
  "email": "kkafka@gmail.com",
  "address": "giridih, jharkhand",
  "registeredDate": "2025-10-18",
  "dateOfBirth": "2003-06-21"
}